[package]
name = "img_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rocket = "0.4.11"
rocket = {path = "Rocket/core/lib"}
serde_json = "1.0.82"
serde = "1.0.138"
